[project]
name = "timeteller-workspace"
version = "1.0.0rc1"
requires-python = ">=3.11"
dependencies = []

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "packages/timeteller",
    "packages/timeteller-cli",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "ruff>=0.15.11",
    "time-machine>=3.2.0",
]
